version: "3"

services:
  wallet-backend:
    build:
      context: ../
      dockerfile: build/Dockerfile
    environment:
      - GIN_MODE=release
    ports:
      - "9001:8080"
    volumes:
      - ../configs/deploy.yaml:/app/configs/main.yaml
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine3.20
    environment:
      POSTGRES_DB: "wallet-db"
      POSTGRES_USER: "wallet-user"
      POSTGRES_PASSWORD: "b1097a3d45b57ae34507"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "9007:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet-user -d wallet-db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G

volumes:
  pgdata:
